services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./docker/elasticmq.conf:/opt/elasticmq.conf
      - elasticmq:/data
  mailpit:
    image: axllent/mailpit:latest
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres:
  elasticmq:
  mailpit:
